version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - mcp_server

  mcp_server:
    build:
      context: ./backend_mcp_server
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mcp_db
    depends_on:
      - db
    ports:
      - "5000:5000"

  rag_agent:
    build:
      context: ./backend_rag_agent
    ports:
      - "8001:8001"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mcp_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
